@startuml
participant Home
participant Webhook
participant Archipels
Home -> Archipels : 1 - verify-age link
Archipels -> Webhook: 2 - MessageReceived /verify-age
Webhook -> Archipels: 3 - send presentation request [over18]
Archipels -> Webhook: 4 - PresentationReceived [over18]
Archipels -> Home: 5 - redirect to secured page
@enduml 